// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valoris.Api.Data;

#nullable disable

namespace Valoris.Api.Migrations
{
    [DbContext(typeof(ValorisDbContext))]
    [Migration("20260513063626_AddGebruikerWachtwoordHash")]
    partial class AddGebruikerWachtwoordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Valoris.Api.Data.Entities.Domein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int>("Basisperiode")
                        .HasColumnType("int");

                    b.Property<decimal>("Interventiedrempel")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Domeinen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.DomeinIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int>("DomeinId")
                        .HasColumnType("int");

                    b.Property<int>("IndicatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomeinId");

                    b.HasIndex("IndicatorId");

                    b.ToTable("DomeinIndicatoren");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Gebruiker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WachtwoordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gebruikers");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.GebruikerDomeinRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DomeinId")
                        .HasColumnType("int");

                    b.Property<int>("GebruikerId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomeinId");

                    b.HasIndex("GebruikerId");

                    b.HasIndex("RolId");

                    b.ToTable("GebruikerDomeinRollen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Indicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int>("Aggregatiewijze")
                        .HasColumnType("int");

                    b.Property<string>("Eenheid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Indicatoren");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Meting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bron")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Gevalideerd")
                        .HasColumnType("bit");

                    b.Property<int>("MetingsdoelId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waarde")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MetingsdoelId");

                    b.HasIndex("PeriodeId");

                    b.ToTable("Metingen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Metingsdoel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<int>("DomeinIndicatorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gewicht")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("NormRichting")
                        .HasColumnType("int");

                    b.Property<decimal>("NormWaarde")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ZaaksoortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomeinIndicatorId");

                    b.HasIndex("ZaaksoortId");

                    b.ToTable("Metingsdoelen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Periode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Einddatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Periodes");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rollen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Veranderimpact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MetingsdoelId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodeId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VeranderingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waarde")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MetingsdoelId");

                    b.HasIndex("PeriodeId");

                    b.HasIndex("VeranderingId");

                    b.ToTable("Veranderimpacten");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Verandering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DomeinId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Einddatum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kosten")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("int");

                    b.Property<DateTime>("Startdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomeinId");

                    b.ToTable("Veranderingen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Zaaksoort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<string>("Behandeling")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DomeinId")
                        .HasColumnType("int");

                    b.Property<string>("Icoon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Volgorde")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DomeinId", "Volgorde")
                        .IsUnique();

                    b.ToTable("Zaaksoorten");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.DomeinIndicator", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.Domein", "Domein")
                        .WithMany("DomeinIndicatoren")
                        .HasForeignKey("DomeinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Indicator", "Indicator")
                        .WithMany("DomeinIndicatoren")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domein");

                    b.Navigation("Indicator");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.GebruikerDomeinRol", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.Domein", "Domein")
                        .WithMany("GebruikerDomeinRollen")
                        .HasForeignKey("DomeinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Gebruiker", "Gebruiker")
                        .WithMany("DomeinRollen")
                        .HasForeignKey("GebruikerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Rol", "Rol")
                        .WithMany("GebruikerDomeinRollen")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domein");

                    b.Navigation("Gebruiker");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Meting", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.Metingsdoel", "Metingsdoel")
                        .WithMany("Metingen")
                        .HasForeignKey("MetingsdoelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Periode", "Periode")
                        .WithMany("Metingen")
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Metingsdoel");

                    b.Navigation("Periode");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Metingsdoel", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.DomeinIndicator", "DomeinIndicator")
                        .WithMany("Metingsdoelen")
                        .HasForeignKey("DomeinIndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Zaaksoort", "Zaaksoort")
                        .WithMany("Metingsdoelen")
                        .HasForeignKey("ZaaksoortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DomeinIndicator");

                    b.Navigation("Zaaksoort");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Veranderimpact", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.Metingsdoel", "Metingsdoel")
                        .WithMany("Veranderimpacten")
                        .HasForeignKey("MetingsdoelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Periode", "Periode")
                        .WithMany("Veranderimpacten")
                        .HasForeignKey("PeriodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Valoris.Api.Data.Entities.Verandering", "Verandering")
                        .WithMany("Veranderimpacten")
                        .HasForeignKey("VeranderingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metingsdoel");

                    b.Navigation("Periode");

                    b.Navigation("Verandering");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Verandering", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.Domein", "Domein")
                        .WithMany("Veranderingen")
                        .HasForeignKey("DomeinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domein");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Zaaksoort", b =>
                {
                    b.HasOne("Valoris.Api.Data.Entities.Domein", "Domein")
                        .WithMany("Zaaksoorten")
                        .HasForeignKey("DomeinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domein");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Domein", b =>
                {
                    b.Navigation("DomeinIndicatoren");

                    b.Navigation("GebruikerDomeinRollen");

                    b.Navigation("Veranderingen");

                    b.Navigation("Zaaksoorten");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.DomeinIndicator", b =>
                {
                    b.Navigation("Metingsdoelen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Gebruiker", b =>
                {
                    b.Navigation("DomeinRollen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Indicator", b =>
                {
                    b.Navigation("DomeinIndicatoren");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Metingsdoel", b =>
                {
                    b.Navigation("Metingen");

                    b.Navigation("Veranderimpacten");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Periode", b =>
                {
                    b.Navigation("Metingen");

                    b.Navigation("Veranderimpacten");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Rol", b =>
                {
                    b.Navigation("GebruikerDomeinRollen");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Verandering", b =>
                {
                    b.Navigation("Veranderimpacten");
                });

            modelBuilder.Entity("Valoris.Api.Data.Entities.Zaaksoort", b =>
                {
                    b.Navigation("Metingsdoelen");
                });
#pragma warning restore 612, 618
        }
    }
}
